### ISSUE TITLE
Empty geolocated_ents with long documents and or 

### ISSUE THREAD

**Issue by dysby** [ahalterman/mordecai3#11]
Hello, 

I'm using mordecai v3 to parse some documents I already had parsed with mordecai v2, and found that v3 detected less geolocations.

First I thought it was due to long document size, but found also found some words that lead to empty geolocated_ents, like the example bellow.

```
>>> len(parser.geoparse_doc('Japan, China, Canada, England, France and Germany.')["geolocated_ents"])
6
>>> len(parser.geoparse_doc('Japan, Soviet Union, China, Canada, England, France and Germany.')["geolocated_ents"])
0
```

Thanks,

**Comment by ahalterman** [comment]
Thanks! Yes, the bug arises when Mordecai isn't able to geolocate an entity (in this case, the Soviet Union). I was able to reproduce the bug with other locations that don't have a match in the geonames gazetteer. Example: "Yesterday, the Syrian Army managed to recapture Al-Ba’ir Al-Mar area following intense battles with the Islamic State jihadists".

The bug arises from a mistake in the code [here](https://github.com/ahalterman/mordecai3/blob/main/mordecai3/geoparse.py#L403), where if any location isn't resolved to an entry, it returns an empty list for all the locations.
