### ISSUE TITLE
DocTransformerOutput' object has no attribute 'tensors'

### ISSUE THREAD

**Issue by nafis-saad** [ahalterman/mordecai3#21]
When i finally go and apply this >> geo.geoparse_doc("I visited Alexanderplatz in Berlin.") the " DocTransformerOutput' object has no attribute 'tensors'" error come. I have check the requirement with mordecai 3 but can not find out the solution.

**Comment by rikukawamura** [comment]
I have been confusing same issue…
If someone find solution, please share!!

**Comment by ahalterman** [comment]
I'm able to replicate the bug by using the latest version of spaCy. I think something has changed in how spacy-transformers exposes the tensors. I'll start on a solution.

**Comment by rikukawamura** [comment]
Thank you for reply, ahalterman.
I appreciate it if you share your spaCy version that you success to execute.
Thanks for your cooperation!!

**Comment by GandCrab** [comment]
> Thank you for reply, ahalterman. I appreciate it if you share your spaCy version that you success to execute. Thanks for your cooperation!!

As a workaround in the meantime, rollback to spacy 3.6.1 and the associated model:
pip install spacy==3.6.1
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.6.1/en_core_web_trf-3.6.1.tar.gz

geo.geoparse_doc should now work again, until there is a fix.

**Comment by ahalterman** [comment]
I haven't forgotten about this issue and I'm working on getting Mordecai 3 compatible with spaCy 3.7+. The way spaCy stores the `tensor` object changed with 3.7 and I'm waiting for some guidance from the spaCy team on where those tensors are stored. [spaCy issue](https://github.com/explosion/spaCy/issues/13137)

**Comment by ahalterman** [comment]
The spaCy people helped me sort out the new tensor format ([issue](https://github.com/explosion/spaCy/issues/13137)), but I still need to retrain the models to handle the new tensors in the updated models. Hopefully I'll get that done in the next few days and then I can close the issue.

**Comment by gimbear** [comment]
Hi @ahalterman,

I hope you're well. I just wanted to check in on this issue to see if there have been any updates or if there are potential fixes on the horizon.

Thanks a ton for all the hard work you've put into mordecai3 - it's a really fascinating project!

**Comment by Aryan-Deshpande** [comment]
Hey i was trying to fix this issue, by downloading the requirements.txt file although, I'm still getting the issue "chunk_len = len(doc._.trf_data.tensors[0][0])
AttributeError: 'DocTransformerOutput' object has no attribute 'tensors'"
