### ISSUE TITLE
Perfect single matches omitted in results

### ISSUE THREAD

**Issue by LorenzBuehmann** [ahalterman/mordecai3#6]
Hi,

first of all thanks for this very useful project.

I think I might have found some issue or limitation, not sure.

Version: 3.0.0a0 installed via PIP.

Input text is _"Kawumu in Uganda"_ and the returned result is then empty although the data is contained in Geonames.

I debugged the code and the Elasticsearch indeed found a match for _"Kawumu"_. It also gets a score of `1.0`. The lines in code where the result is lost or better said omitted is at https://github.com/ahalterman/mordecai3/blob/764faefc0b35a68526860569a283ab8243a07ed9/mordecai3/geoparse.py#L381-L382

At this part, the scores array contains a single entry with score `1.0`, thus, the position of the best score is trivially at index `0` and this matches the condition for early termination. But, at this point in time no result has been attached to the `output` object. Is this intended and I'm missing something? 

Thanks in advance.

**Comment by ahalterman** [comment]
Thanks for the detailed bug report! I'll take a look tonight. 

For context, selecting the final candidate location is equivalent to picking "none of the above". During training, I omit the correct candidate location for some training examples, and then set the final entry in the candidate list to a null answer and label that final candidate as the correct answer. This was meant to reduce the confidence of the model when the correct answer isn't present. But in this case, the correct answer is clearly there, so there's a mistake happening somewhere.

**Comment by ahalterman** [comment]
Yes, this is a mistake exactly like you describe it. This also came up in #11. It should be closed by [80541ef](https://github.com/ahalterman/mordecai3/commit/80541ef1b357bd6d297b07cc2da485ab9f4d3d22).
